In [1]:
import pandas as pd
import json
import numpy as np
filepath = 'C:/Users/Playdata/Downloads/대학교 자료/erd_data2/rdb_schools.json'

with open(filepath) as f:
    school_data = json.loads(f.read())

school_df = pd.DataFrame(school_data)
school_df.isna().sum()
# req join 용 
school_name = school_df

school_df = school_df[['name', 'country', 'address']]
school_df = school_df.rename(columns = {'address': 'location'})

school_df.to_csv('school_df.csv',index=False)
school_df

                                      name country                 location
0                      New York University     USA             New York, NY
1        University of Southern California     USA  Los Angeles, California
2  University of Illinois Urbana-Champaign     USA         Urbana, IL 61801
3                      Columbia University     USA             New York, NY
4    University of California, Los Angeles     USA          Los Angeles, CA
5                        Boston University     USA               Boston, MA
6       University of California, Berkeley     USA             Berkeley, CA
7      University of California, San Diego     USA             La Jolla, CA
8                        Purdue University     USA       West Lafayette, IN
9        The Pennsylvania State University     USA      University Park, PA

In [2]:
import pandas as pd
from datetime import datetime

filepath = 'C:/Users/Playdata/Downloads/대학교 자료/erd_data2/rdb_admissions.json'

with open(filepath) as f:
    admissions_data = json.loads(f.read())

admissions_df = pd.DataFrame(admissions_data)
admissions_df.loc[admissions_df['admission_id']=='UCBerkeley_ADM', 'tuition']=79881
admissions_df.loc[admissions_df['admission_id']=='PennState_ADM', 'tuition']=92000
admissions_df
# 79,881  / 92000
# # school_df.isna().sum()
admissions_df['name'] = school_df['name']
admissions_df = admissions_df[['name', 'regular_deadline', 'early_deadline', 'tuition']]
admissions_df


# 날짜 전처리
current_year = datetime.now().year

def convert_deadline(series):
    with_year = series.apply(
        lambda x: f"{x} {current_year}" if isinstance(x, str) else x
    )
    as_dt = pd.to_datetime(with_year, errors='coerce')  # format 제거
    return as_dt.apply(lambda x: x.strftime('%Y-%m-%d') if pd.notna(x) else None)

admission_df = admissions_df.copy()
admission_df['regular_deadline'] = convert_deadline(admission_df['regular_deadline'])
admission_df['early_deadline'] = convert_deadline(admission_df['early_deadline'])

admission_df.to_csv('admission_df.csv',index=False)
admission_df

,name,regular_deadline,early_deadline,tuition
0,New York University,2026-01-01,2026-11-01,60000.0
1,University of Southern California,2026-01-10,2026-11-01,75384.0
2,University of Illinois Urbana-Champaign,2026-01-05,2026-11-01,58316.0
3,Columbia University,2026-01-01,2026-11-01,70170.0
4,"University of California, Los Angeles",2026-12-01,None,80739.0
5,Boston University,2026-01-05,2026-11-02,73024.0
6,"University of California, Berkeley",2026-11-30,None,79881.0
7,"University of California, San Diego",2026-12-01,None,21546.0
8,Purdue University,2026-01-01,2026-11-01,30000.0
9,The Pennsylvania State University,2026-12-01,2026-11-01,92000.0

In [3]:
filepath = 'C:/Users/Playdata/Downloads/대학교 자료/erd_data2/rdb_requirements.json'

with open(filepath) as f:
    requirements_data = json.loads(f.read())

requirements_df = pd.DataFrame(requirements_data)
requirements_df

,document_type,requirement_policy,metric_name,metric_value,notes,requirement_id,school_code
0,TOEFL,Conditionally Required,Competitive Score,100,"No strict minimum, but this is the competitive...",NYU_REQ_1,NYU
1,IELTS,Conditionally Required,Competitive Score,7.5,"No strict minimum, but this is the competitive...",NYU_REQ_2,NYU
2,Duolingo,Conditionally Required,Competitive Score,135,"No strict minimum, but this is the competitive...",NYU_REQ_3,NYU
3,PTE,Conditionally Required,Competitive Score,70,"No strict minimum, but this is the competitive...",NYU_REQ_4,NYU
4,Cambridge English,Conditionally Required,Competitive Score,191,"No strict minimum, but this is the competitive...",NYU_REQ_5,NYU
...,...,...,...,...,...,...,...
62,IELTS,Conditionally Required,Competitive Score,6.5,"No strict minimum, but this is the competitive...",PennState_REQ_2,PennState
63,Duolingo,Conditionally Required,Competitive Score,105,"No strict minimum, but this is the competitive...",PennState_REQ_3,PennState
64,PTE,Conditionally Required,Competitive Score,53,"No strict minimum, but this is the competitive...",PennState_REQ_4,PennState
65,Cambridge English,Conditionally Required,Competitive Score,169,"No strict minimum, but this is the competitive...",PennState_REQ_5,PennState
66,iTEP,Conditionally Required,Competitive Score,3.7,"No strict minimum, but this is the competitive...",PennState_REQ_6,PennState

In [4]:
# 대학교 이름 매칭
req_df = pd.merge(school_name,requirements_df, on = 'school_code', how = 'inner')
requirements_df = req_df[['name', 'document_type', 'metric_name', 'requirement_policy','metric_value', 'notes']]
requirement_df = requirements_df.rename(columns = {
                                 'document_type': 'type',
                                 'metric_name': 'metric_type',
                                 'requirement_policy': 'require',
                                 'metric_value' : 'value'
                                 }) 

requirement_df['value'][41]=125
requirement_df['value'][39]=90
requirement_df.to_csv('requirement_df.csv',index=False)
requirement_df

C:\Users\Playdata\AppData\Local\Temp\ipykernel_47064\3487388839.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  requirement_df['value'][41]=125
C:\Users\Playdata\AppData\Local\Temp\ipykernel_47064\3487388839.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  requirement_df['value'][39]=90

,name,type,metric_type,require,value,notes
0,New York University,TOEFL,Competitive Score,Conditionally Required,100,"No strict minimum, but this is the competitive..."
1,New York University,IELTS,Competitive Score,Conditionally Required,7.5,"No strict minimum, but this is the competitive..."
2,New York University,Duolingo,Competitive Score,Conditionally Required,135,"No strict minimum, but this is the competitive..."
3,New York University,PTE,Competitive Score,Conditionally Required,70,"No strict minimum, but this is the competitive..."
4,New York University,Cambridge English,Competitive Score,Conditionally Required,191,"No strict minimum, but this is the competitive..."
...,...,...,...,...,...,...
62,The Pennsylvania State University,IELTS,Competitive Score,Conditionally Required,6.5,"No strict minimum, but this is the competitive..."
63,The Pennsylvania State University,Duolingo,Competitive Score,Conditionally Required,105,"No strict minimum, but this is the competitive..."
64,The Pennsylvania State University,PTE,Competitive Score,Conditionally Required,53,"No strict minimum, but this is the competitive..."
65,The Pennsylvania State University,Cambridge English,Competitive Score,Conditionally Required,169,"No strict minimum, but this is the competitive..."
66,The Pennsylvania State University,iTEP,Competitive Score,Conditionally Required,3.7,"No strict minimum, but this is the competitive..."

In [9]:
faq_df = pd.read_json('C:/Users/Playdata/Downloads/대학교 자료/erd_data2/rdb_faqs.json')
faq_df = pd.merge(school_name,faq_df, on = 'school_code', how = 'inner')
faq_df = faq_df[['name', 'question', 'answer', 'category']]
faq_df.to_csv('faq_df.csv', index = False)
faq_df

,name,question,answer,category
0,New York University,What are the key deadlines for undergraduate a...,"For undergraduate admissions at NYU, the key d...",Admissions
1,New York University,Is NYU test-optional?,"Yes, NYU is test-optional through the 2026-202...",Admissions
2,New York University,Does NYU meet 100% of demonstrated financial n...,"Yes, NYU will meet 100% of demonstrated financ...",Financial Aid
3,New York University,What English proficiency exams does NYU accept...,Non-native speakers may need to submit scores ...,International Applicants
4,New York University,What is the benefit of Spring Admission at NYU?,Spring Admission allows students to start thei...,Spring Admissions
5,University of Southern California,What are the important application deadlines f...,USC has the following key deadlines: Early Act...,Dates and Deadlines
6,University of Southern California,What is included in the application checklist ...,The application checklist for USC includes: Th...,Admission Requirements
7,University of Southern California,Does USC accept home-schooled students differe...,"Yes, home-schooled students applying to USC mu...",Application Process
8,University of Southern California,Does USC offer need-based financial aid to int...,"No, USC does not provide need-based financial ...",Financial Aid
9,University of Southern California,What are the English proficiency requirements ...,International applicants whose native language...,International Students
10,University of Illinois Urbana-Champaign,What required items do I need to send after I ...,"After submitting your application, you must en...",Applicant
11,University of Illinois Urbana-Champaign,What percentage of applicants get admitted?,"The admission rate varies from year to year, r...",Applicant
12,University of Illinois Urbana-Champaign,Is the ACT or SAT optional for all first-year ...,"Yes, the ACT and SAT are optional for first-ye...",Applicant
13,University of Illinois Urbana-Champaign,How do I check my application status in myIllini?,You can check your application status by loggi...,Applicant
14,University of Illinois Urbana-Champaign,What should I do if I have questions regarding...,"For visa-related questions, please refer to th...",Applicant
15,Columbia University,What is Columbia looking for when evaluating s...,"Columbia reviews applications holistically, co...",Applying
16,Columbia University,How competitive is admission to Columbia?,Admission to Columbia is highly competitive du...,Applying
17,Columbia University,Are there advisers for specific departmental m...,"Yes, Columbia provides academic advisers for e...",Applying
18,Columbia University,Does Columbia allow students to double major?,"Yes, students at Columbia are allowed to doubl...",Applying
19,Columbia University,What are your secondary/high school course req...,Applicants must demonstrate a strong academic ...,Applying
20,Columbia University,"Is there a minimum test score, class rank or G...",Columbia does not set strict minimums for test...,Applying
21,Columbia University,How large are Columbia's classes?,"Columbia classes vary in size, with many gradu...",Applying
22,Columbia University,Is there a maximum number of students admitted...,"No, Columbia does not impose caps on admission...",Applying
23,Columbia University,May I apply to both Columbia College and Colum...,"Yes, students may apply to both Columbia Colle...",Applying
24,Columbia University,When do application decisions become available?,Application decisions are released through the...,Applying
25,Columbia University,What if I need an application deadline extension?,Columbia generally adheres strictly to its dea...,Applying
26,Columbia University,How can I take advantage of everything I want ...,"Columbia offers various resources, programs, a...",Applying
27,Columbia University,Does Columbia grant credit for college courses...,"Yes, Columbia grants credit for eligible colle...",Financial Aid
28,Columbia University,Are students required to live on campus? Can I...,First-year students are required to live on ca...,Financial Aid
29,Columbia University,What is Columbia’s policy on admissions interv...,Interviews are not part of the application pro...,Financial Aid
30,Columbia University,What are the English Proficiency Requirements ...,International applicants must demonstrate prof...,International and Undocumented Students
31,Columbia University,What is Columbia's policy on financial aid for...,Columbia meets 100% of the demonstrated need f...,International and Undocumented Students
32,Boston University,What is Boston University’s test policy?,Boston University will adopt a test optional p...,application process
33,Boston University,What are the Early Decision deadlines for Bost...,The Early Decision application deadline is Nov...,admissions deadlines
34,Boston University,What is the BU Promise?,The BU Promise guarantees that Boston Universi...,financial aid
35,Boston University,How do I apply as a first-year student?,You must submit either the Common Application ...,first-year applicants
36,Boston University,What do international applicants need to submit?,International applicants are required to submi...,international students
37,"University of California, Berkeley",What is the selection process for first-year a...,"UC Berkeley uses a holistic review process, wh...",Application Process
38,"University of California, Berkeley",Does UC Berkeley require standardized test sco...,"No, UC Berkeley is test-free and does not cons...",Standardized Testing
39,"University of California, Berkeley",What is required for international applicants?,International applicants must either require a...,International Students
40,"University of California, Berkeley",What are the costs associated with attending U...,The cost of attendance includes tuition and fe...,Financial Aid
41,"University of California, Berkeley",Are letters of recommendation required for the...,Letters of recommendation are not required but...,Letters of Recommendation
42,"University of California, San Diego",How do I apply to UC San Diego?,You can apply to UC San Diego by submitting th...,Admissions
43,"University of California, San Diego",What majors are offered at UC San Diego?,UC San Diego offers a wide range of majors acr...,Academics & Majors
44,"University of California, San Diego",How much does it cost to attend UC San Diego?,The cost of attendance varies by residency sta...,Cost & Financial Aid
45,"University of California, San Diego",What are A-G requirements?,A-G requirements are a series of college prepa...,First-Year
46,"University of California, San Diego",What English proficiency tests are accepted fo...,International students must demonstrate Englis...,International Students
47,Purdue University,What is the application process for Purdue Uni...,"To apply to Purdue University, first-year stud...",Admissions
48,Purdue University,What are the application deadlines for Purdue ...,The application deadline for Early Action is N...,Admissions
49,Purdue University,What are the SAT/ACT requirements for Purdue U...,Purdue accepts both SAT and ACT scores without...,Admissions
50,Purdue University,What are the English proficiency requirements ...,International students whose primary language ...,International Students
51,Purdue University,What are the tuition and fee rates for 2025-2026?,Tuition rates vary based on the program of stu...,Tuition and Fees
52,The Pennsylvania State University,What is the application fee for Penn State?,The application fee for domestic students is $...,application
53,The Pennsylvania State University,What are the Early Action and Priority Admissi...,"The Early Action Deadline is November 1, and t...",admissions
54,The Pennsylvania State University,What are the minimum high school course requir...,"For a four-year degree, students must complete...",requirements
55,The Pennsylvania State University,What are the steps for international students ...,International students should research program...,international
56,The Pennsylvania State University,What is the GPA range for the middle 50% of ad...,The middle 50% GPA for admitted students at Un...,eligibility